### ISSUE TITLE
DMA with Timeout using USART_RTOR

### ISSUE THREAD

**Issue by juan0fran** [akospasztor/stm32-dma-uart#1]
Hi,

I am developing an application using some USART features over a STM32L4 which is running a FreeRTOS. 

The point is DMA is mandatory as well if I want to run it at a "decent" speed. I liked your idea but I would suggest to move from a "systick based" timer to use the ISR produced by USART Receiver Timeout, which can be set in terms of bit time.

Take a look to: (USART_RTOR and USART_ISR -> RTOEN)

http://www.st.com/content/ccc/resource/technical/document/reference_manual/02/35/09/0c/4f/f7/40/03/DM00083560.pdf/files/DM00083560.pdf/jcr:content/translations/en.DM00083560.pdf

Even tho, I am not getting why you are not using the ISR linked to Half/Transfer for DMA, may you loose a byte on the DMA channel?

**Comment by akospasztor** [comment]
Hi,

Wow, thanks for the hint! to be honest, I didn't know that this feature exists (in the STM32L4xx family). I will implement this and push it to GitHub as soon as I have a bit of free time. 

About the half-transfer interrupt: in many scenarios, it can be really useful. However this DMA timeout is mainly made for receiving GPS RAW data over hi-speed UART, using FreeRTOS as well. The biggest problem is that the size of the incoming packets in each second varies (based on position, space vehicles, etc.), so it cannot be predicted how much data will be received in the next second. Moreover, there is no special character at the end of a packet to determine the last byte of the packet. This is the reason why I'm using the timeout event to determine the end of a packet, so basically the timeout event signals that there is a packet fully received and the data can be processed. However, if you have a more clever idea or solution, then please share it :)

**Comment by juan0fran** [comment]
Hi, 

I am using as well the UART with DMA for non-static-size packets! The use of Half Transfer DMA can be useful if you do not have enough time to empty the DMA buffer and more bytes are coming from the USART. Using Half and Cplt transfer makes the system to have a "kind-of" dual DMA buffer.

I have an implementation of that on a github repo, please check:

https://github.com/juan0fran/STM32L4_CC1101

Is a bit messy as is still in a prototype version.

In the file tree, you can find in Src/usart.c all code related to USART initialization as well as the DMA callbacks executed. Note that in that a file a Initialization function is set which makes the DMA_Rx_Start as well as sets the RTO flags for the USART interface.

Take a look as well to Src/stm32l4xx_it.c, where is the USART IRQ handler, which has been a bit modified in order to include the managing of RTOF events.

In my case I am also determining the size of the packet by means of this timeout. In fact, the only work that I am doing is to pass all the buffer information from the DMA circular queue to a FreeRTOS queue. Outside the ISR, in a FreeRTOS task, the FreeRTOS queue is picked up and the bytes from the USART processed.

**Comment by akospasztor** [comment]
Thanks a lot for the info and resources, I'm gonna have a look at your implementation!

**Comment by asund** [comment]
I'm looking at this stuff for work and hope to jump in to contribute if time permits.

I am using an L1 chip without a receiver timeout register, so I will still need to hook into a timer to drive functionality, unless you think using the receiver idle interrupt would work. Basically an unconfigurable timeout register. Might be prone to firing all the time if the remote transmitter isn't sending bytes fast enough.

Also, using both the transfer complete and half transfer interrupts to read out half of the DMA's circular buffer each time one of them fires seems like the best solution.

EDIT:
How about this for a timerless solution for those of us without a timeout register: When initializing the receiver the RXNE interrupt is enabled. When RXNE fires it disables itself and enables the IDLE interrupt. When the IDLE interrupt fires, it disables itself and enables the RXNE interrupt, as well as cleaning out whatever's sitting in the DMA's circular buffer, updating prevCNDTR, etc. This is at worst two interrupts per character received, but that worst case is going to be slow enough that two ISRs shouldn't matter and the interrupt priority can be set low because it's only handling timeout events.
